# Generated by Django 4.2 on 2024-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=6, verbose_name='Price')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
