# Generated by Django 4.2 on 2024-12-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
